// Auto-generated calibration data header file
// Source: lamp03.json
// Generated by: convert_calibration.py
// DO NOT EDIT THIS FILE MANUALLY - Regenerate using the script instead

#pragma once
#include <stdint.h>

// Calibration data for lamp03
// Order: base_yaw(1), base_pitch(2), elbow_pitch(3), wrist_roll(4), wrist_pitch(5)

// Homing offset values (register values) for 5 servos
const int16_t servo_homing_offsets[5] = {
    -1437,  // ID 1: base_yaw
    1470,   // ID 2: base_pitch
    -1302,  // ID 3: elbow_pitch
    725,    // ID 4: wrist_roll
    -1259   // ID 5: wrist_pitch
};

// Range minimum values (register values) for 5 servos
const uint16_t servo_range_min[5] = {
    795,   // ID 1: base_yaw
    929,   // ID 2: base_pitch
    878,   // ID 3: elbow_pitch
    855,   // ID 4: wrist_roll
    193    // ID 5: wrist_pitch
};

// Range maximum values (register values) for 5 servos
const uint16_t servo_range_max[5] = {
    3379,  // ID 1: base_yaw
    3180,  // ID 2: base_pitch
    3064,  // ID 3: elbow_pitch
    3165,  // ID 4: wrist_roll
    4012   // ID 5: wrist_pitch
};

// Calibration source info
#define CALIBRATION_LAMP_ID "lamp03"






