// Auto-generated calibration data header file
// Source: lamp0324.json
// Generated by: convert_calibration.py
// DO NOT EDIT THIS FILE MANUALLY - Regenerate using the script instead

#pragma once
#include <stdint.h>

// Calibration data for lamp0324
// Order: base_yaw(1), base_pitch(2), elbow_pitch(3), wrist_roll(4), wrist_pitch(5)

// Homing offset values (register values) for 5 servos
const int16_t servo_homing_offsets[5] = {
    -1689,  // ID 1: base_yaw
    -699,  // ID 2: base_pitch
    -822,  // ID 3: elbow_pitch
    -901,  // ID 4: wrist_roll
    1402   // ID 5: wrist_pitch
};

// Range minimum values (register values) for 5 servos
const uint16_t servo_range_min[5] = {
    1092,  // ID 1: base_yaw
    908,  // ID 2: base_pitch
    937,  // ID 3: elbow_pitch
    833,  // ID 4: wrist_roll
    167   // ID 5: wrist_pitch
};

// Range maximum values (register values) for 5 servos
const uint16_t servo_range_max[5] = {
    3272,  // ID 1: base_yaw
    2992,  // ID 2: base_pitch
    3126,  // ID 3: elbow_pitch
    3092,  // ID 4: wrist_roll
    3400   // ID 5: wrist_pitch
};

// Calibration source info
#define CALIBRATION_LAMP_ID "lamp0324"

// ============================================
// High-level lamp0324 presets (logical angles)
// These are lerobot-compatible angles in degrees for the 5 joints:
// [base_yaw, base_pitch, elbow_pitch, wrist_roll, wrist_pitch]
// ============================================

typedef struct {
    const char* name;
    float angles[5];
} Lamp0324Preset;

// Presets for lamp0324 model.
static const Lamp0324Preset kLamp0324Presets[] = {
    // Stable boot-aligned neutral pose.
    {"home",       {0.0f, 64.0f, 0.0f, 58.0f, -98.0f}},
    // Forward horizontal lighting pose.
    {"horizontal", {0.0f, 90.0f, 0.0f, 58.0f, -90.0f}},
    // Upward vertical lighting pose.
    {"vertical",   {0.0f, 20.0f, -45.0f, 58.0f, -60.0f}},
};

static const int kLamp0324PresetCount =
    sizeof(kLamp0324Presets) / sizeof(kLamp0324Presets[0]);
