// Auto-generated calibration data header file
// Source: lamp05.json
// Generated by: convert_calibration.py
// DO NOT EDIT THIS FILE MANUALLY - Regenerate using the script instead

#pragma once
#include <stdint.h>

// Calibration data for lamp05
// Order: base_yaw(1), base_pitch(2), elbow_pitch(3), wrist_roll(4), wrist_pitch(5)

// Homing offset values (register values) for 5 servos
const int16_t servo_homing_offsets[5] = {
    -589,  // ID 1: base_yaw
    -1575,  // ID 2: base_pitch
    200,  // ID 3: elbow_pitch
    1140,  // ID 4: wrist_roll
    -1428   // ID 5: wrist_pitch
};

// Range minimum values (register values) for 5 servos
const uint16_t servo_range_min[5] = {
    1077,  // ID 1: base_yaw
    1157,  // ID 2: base_pitch
    0,  // ID 3: elbow_pitch
    909,  // ID 4: wrist_roll
    870   // ID 5: wrist_pitch
};

// Range maximum values (register values) for 5 servos
const uint16_t servo_range_max[5] = {
    3059,  // ID 1: base_yaw
    2781,  // ID 2: base_pitch
    4095,  // ID 3: elbow_pitch
    3131,  // ID 4: wrist_roll
    3007   // ID 5: wrist_pitch
};

// Calibration source info
#define CALIBRATION_LAMP_ID "lamp05"

// ============================================
// High-level lamp05 presets (logical angles)
// These are lerobot-compatible angles in degrees for the 5 joints:
// [base_yaw, base_pitch, elbow_pitch, wrist_roll, wrist_pitch]
// WARNING: This section is hand-maintained; adjust carefully when
// regenerating calibration data.
// ============================================

typedef struct {
    const char* name;
    float angles[5];
} Lamp05Preset;

// Example presets for lamp05 model
static const Lamp05Preset kLamp05Presets[] = {
    // Neutral pose, roughly facing forward at comfortable height
    {"home",       {-2.0f,  50.0f,  0.0f,   5.0f,  60.0f}},
    // Horizontal extension forward
    {"horizontal", {-2.0f,  99.0f,  0.0f,   5.0f,  67.0f}},
    // Vertical up pose
    {"vertical",   {-2.0f,  10.0f, -54.0f,  5.0f, 100.0f}},
};

static const int kLamp05PresetCount = sizeof(kLamp05Presets) / sizeof(kLamp05Presets[0]);

